test_configuration:
  target: ReachyUI
  test_target_path: ${PROJECT_DIR}/ReachyUISnapshotTests
  sources:
    - ${PROJECT_DIR}/../Sources/ReachyUI/Previews
    - ${PROJECT_DIR}/ReachySpike/Previews
  testable_imports:
    - ReachyKit
  snapshot_devices:
    - iPhone 16 Pro
    - iPad Pro 11
  simulator_device: "iPhone18,1"
  required_os: 26
  use_grouped_snapshots: false
  split_snapshot_directories: true
  preview_default_enabled: true

playbook_configuration:
  preview_default_enabled: true
  testable_imports:
    - ReachyUI
    - ReachyKit
